Remove circular dependency
The gem should not depend on itself. This causes installation to fail:

```
% gem install scheduler_daemon:1.1.6
ERROR:  While executing gem ... (Gem::Resolver::Molinillo::CircularDependencyError)
    There is a circular dependency between scheduler_daemon
```